insert into public.sources(id,name,url,publisher) values
('tnauTomato','TNAU Agritech Portal — Tomato diseases','https://agritech.tnau.ac.in/crop_protection/crop_prot_crop%20diseases_veg_tomato.html','TNAU Agritech Portal'),
('tnauCrops','TNAU Agritech Portal — Crop protection','https://agritech.tnau.ac.in/crop_protection/crop_protection.html','TNAU Agritech Portal'),
('ppqs','Government of India PPQS — IPM packages','https://ppqs.gov.in/ipm-packages','Government of India PPQS'),
('plantVillage','PlantVillage image dataset','https://github.com/spMohanty/PlantVillage-Dataset','PlantVillage image dataset')
on conflict(id) do update set name=excluded.name,url=excluded.url,publisher=excluded.publisher,accessed_on=current_date;

insert into public.conditions(id,crop,name,condition_type,affected_parts,symptoms,confirmation,actions,source_id) values
('tom-early','Tomato','Early blight','Disease',array['leaf','stem','fruit']::text[],array['Brown target-like rings, usually first on older leaves','Yellow tissue around expanding lesions']::text[],'Check concentric rings and whether older foliage is affected first.',array['Remove infected crop debris','Improve airflow and avoid prolonged leaf wetness','Use only a locally registered treatment after expert confirmation']::text[],'tnauTomato'),
('tom-late','Tomato','Late blight','Disease',array['leaf','stem','fruit']::text[],array['Rapidly expanding water-soaked brown lesions','Pale growth near lesion edge in humid weather']::text[],'Inspect leaf undersides early morning and consider recent cool, humid weather.',array['Separate the affected zone','Avoid moving wet foliage between rows','Seek urgent local plant-pathology guidance']::text[],'tnauTomato'),
('tom-wilt','Tomato','Wilt complex','Disease',array['root','stem','whole plant']::text[],array['Sudden or progressive wilting','Brown vascular tissue may be visible inside stem']::text[],'Use a clean stem check with expert guidance and confirm in a lab where possible.',array['Mark affected plants','Do not move contaminated soil or tools','Use rotation and locally recommended sanitation']::text[],'tnauTomato'),
('tom-curl','Tomato','Leaf curl complex','Disease',array['leaf','whole plant']::text[],array['Upward curling and reduced leaf size','Stunting; whiteflies may be present']::text[],'Inspect new growth and vector pressure; rule out herbicide and nutrient stress.',array['Control vectors using IPM','Remove severe sources under local guidance','Use healthy planting material']::text[],'ppqs'),
('tom-borer','Tomato','Fruit borer','Pest',array['flower','fruit']::text[],array['Entry holes with frass','Larva feeding inside fruit']::text[],'Inspect damaged fruit and nearby flowers for larvae or eggs.',array['Collect damaged fruits','Use pheromone monitoring where recommended','Act only after threshold-based scouting']::text[],'ppqs'),
('chi-anth','Chilli','Anthracnose / fruit rot','Disease',array['fruit','stem']::text[],array['Dark sunken fruit lesions','Orange or pink spore masses in humidity']::text[],'Check whether lesions are sunken and expanding on mature fruit.',array['Remove infected fruit','Reduce splash and injury','Use clean seed and local guidance']::text[],'tnauCrops'),
('chi-curl','Chilli','Leaf curl complex','Disease',array['leaf','whole plant']::text[],array['Curling, puckering and shortened internodes','Stunting with possible vector insects']::text[],'Inspect new leaves and scout whiteflies, thrips and mites.',array['Manage vectors with IPM','Remove alternate weed hosts','Use tolerant material where recommended']::text[],'ppqs'),
('chi-thrips','Chilli','Thrips injury','Pest',array['leaf','flower','fruit']::text[],array['Silvery scraping and upward curling','Tiny insects in flowers or leaf folds']::text[],'Tap flowers over white paper and inspect with magnification.',array['Monitor natural enemies','Remove weed hosts','Use controls only after threshold confirmation']::text[],'ppqs'),
('chi-mite','Chilli','Broad mite injury','Pest',array['leaf','bud']::text[],array['Downward curling and hardened narrow leaves','Bronzed tender growth']::text[],'Inspect tender growth with magnification and rule out virus.',array['Avoid unnecessary broad-spectrum sprays','Conserve natural enemies','Use registered control only after confirmation']::text[],'ppqs'),
('mai-faw','Maize','Fall armyworm','Pest',array['leaf','whorl','cob']::text[],array['Window-pane feeding and ragged whorl damage','Fresh frass deep in the whorl']::text[],'Inspect the whorl for larvae and record affected plants per sample.',array['Scout from early crop stage','Conserve natural enemies','Follow official threshold-based whorl management']::text[],'ppqs'),
('mai-tlb','Maize','Turcicum leaf blight','Disease',array['leaf']::text[],array['Long cigar-shaped grey-green lesions','Lesions merge and dry large areas']::text[],'Check lesion shape and crop stage; distinguish from other blights.',array['Use resistant hybrids where suitable','Manage infected residue','Seek treatment advice only if economically justified']::text[],'tnauCrops'),
('mai-stem','Maize','Stem borer','Pest',array['leaf','stem','whorl']::text[],array['Pin holes on emerging leaves','Dead heart or stem tunnelling']::text[],'Inspect whorl and split a damaged stem for larvae or frass.',array['Scout early stages','Manage infested residue after harvest','Use official threshold-based IPM']::text[],'ppqs'),
('mai-zinc','Maize','Suspected zinc deficiency','Nutrient stress',array['leaf']::text[],array['Broad pale bands beside the midrib','Young plants may be stunted']::text[],'Confirm with soil or tissue testing and rule out root damage.',array['Request a soil/tissue test','Correct pH or nutrient source from test','Calculate dose only from area, test and product analysis']::text[],'tnauCrops'),
('cot-pink','Cotton','Pink bollworm','Pest',array['flower','boll','seed']::text[],array['Rosette flowers or internal boll feeding','Poor boll opening and damaged seed']::text[],'Open sampled bolls and use trap/scouting records.',array['Destroy residues as directed','Use timely harvest and resistance management','Act only from threshold-based advice']::text[],'ppqs'),
('cot-suck','Cotton','Sucking-pest complex','Pest',array['leaf','bud']::text[],array['Leaf curling, yellowing or honeydew','Aphids, jassids, whiteflies or thrips underneath']::text[],'Identify species and count per leaf before choosing control.',array['Conserve natural enemies','Avoid unnecessary broad-spectrum sprays','Use official economic thresholds']::text[],'ppqs'),
('cot-blight','Cotton','Bacterial blight','Disease',array['leaf','stem','boll']::text[],array['Angular water-soaked leaf spots','Black arm lesions or boll spotting']::text[],'Look for angular lesions limited by veins and inspect stems.',array['Use clean seed and resistant varieties','Avoid working wet crops','Manage residue locally']::text[],'tnauCrops'),
('cot-wilt','Cotton','Fusarium wilt','Disease',array['root','stem','whole plant']::text[],array['Yellowing and progressive wilt','Brown vascular discoloration']::text[],'Check lower-stem vascular browning and nematode interaction.',array['Map affected patches','Use rotation and resistant varieties','Improve soil health with local advice']::text[],'tnauCrops'),
('gnt-els','Groundnut','Early leaf spot','Disease',array['leaf','petiole','stem']::text[],array['Brown spots often with yellow halo','Defoliation as disease advances']::text[],'Check both leaf surfaces and compare with late leaf spot.',array['Manage volunteer hosts and residue','Improve canopy airflow','Follow integrated disease guidance']::text[],'tnauCrops'),
('gnt-lls','Groundnut','Late leaf spot','Disease',array['leaf','petiole','stem']::text[],array['Dark brown to black spots','Severe defoliation']::text[],'Inspect lower leaf surface and distinguish from rust.',array['Scout after canopy closure','Use resistant varieties','Use local disease program after confirmation']::text[],'tnauCrops'),
('gnt-rust','Groundnut','Rust','Disease',array['leaf']::text[],array['Orange-brown pustules below leaves','Yellowing and premature leaf fall']::text[],'Inspect raised pustules with magnification.',array['Remove volunteer plants','Monitor spread in humid weather','Seek registered management advice']::text[],'tnauCrops'),
('gnt-collar','Groundnut','Collar/root rot','Disease',array['root','collar','seedling']::text[],array['Seedling collapse and dark collar lesion','Root or collar decay']::text[],'Inspect collar and roots and map drainage relationship.',array['Improve drainage','Use healthy treated seed under official guidance','Avoid moving contaminated soil']::text[],'tnauCrops'),
('gnt-miner','Groundnut','Leaf miner','Pest',array['leaf']::text[],array['Serpentine mines or folded leaflets','Larva within mined tissue']::text[],'Open a fresh mine and sample affected leaflets.',array['Conserve parasitoids','Remove alternate hosts where appropriate','Use threshold-based management']::text[],'ppqs')
on conflict(id) do update set crop=excluded.crop,name=excluded.name,condition_type=excluded.condition_type,affected_parts=excluded.affected_parts,symptoms=excluded.symptoms,confirmation=excluded.confirmation,actions=excluded.actions,source_id=excluded.source_id,updated_at=now();
