const app = document.getElementById('app');

const modules = [
  ['overview','⌂','Overview'],['farm','▦','My Farm'],['monitoring','◉','Live Monitoring'],['weather','☀','Weather Intelligence'],
  ['crop-health','◒','Crop Health'],['disease','⚠','Disease & Pest AI'],['advisory','✦','AI Advisory'],['memory','◎','Crop Memory'],
  ['treatment','✚','Treatment Center'],['irrigation','◌','Irrigation'],['nutrients','⚗','Nutrients & Fertilizer'],['weeds','♧','Weed Intelligence'],
  ['drone','◇','Drone Missions'],['rover','⬡','Rover Control'],['harvest','◈','Harvest Intelligence'],['store','▣','AgriStore'],
  ['loss','◫','Crop Loss & Evidence'],['market','₹','AgriMarket 2.0'],['collect','⇄','AgriCollect'],['encyclopedia','▤','Crop Encyclopedia'],
  ['schemes','⌘','Government Schemes'],['reports','▧','Reports'],['alerts','!','Alerts'],['agrisathi','◍','AgriSathi'],['settings','⚙','Settings']
];

const crops = [
  ['Tomato','Early blight','Moderate','92%','Plot A · Row 4','🍅'],
  ['Chilli','Thrips pattern','High','89%','Plot B · Row 6','🌶️'],
  ['Maize','Leaf blight pattern','Low','87%','Plot C · Row 2','🌽'],
  ['Groundnut','Leaf spot pattern','Moderate','90%','Plot D · Zone 3','🥜'],
  ['Cotton','Bacterial blight pattern','Low','84%','Plot E · Row 8','🌿']
];

function topbar(){
  return `<header class="topbar">
    <div class="brand" onclick="home()" style="cursor:pointer"><div class="brand-mark">🌿</div><div><strong>AgriGuardian X</strong><small>FARM OPERATING SYSTEM</small></div></div>
    <nav class="navlinks"><a href="#problem">Problem</a><a href="#platform">Platform</a><a href="#market">Startup</a><a href="#crops">Crop Intelligence</a></nav>
    <div class="top-actions"><button class="btn btn-soft" onclick="toast('AgriSathi is ready in local-language farmer mode.')">🎙 AgriSathi</button><button class="btn btn-primary" onclick="dash('overview')">Open Dashboard →</button></div>
  </header>`;
}

function footer(){
  return `<footer class="footer"><div class="footer-grid"><div><h3>AgriGuardian X</h3><p>Rural-first crop intelligence, precision intervention, recovery verification and buyer-facing crop trust.</p></div><div><h3>Platform</h3><ul><li>Crop Intelligence</li><li>Precision Treatment</li><li>Crop Memory</li><li>AgriMarket 2.0</li></ul></div><div><h3>Startup</h3><ul><li>FPO service model</li><li>Per-acre services</li><li>Buyer traceability</li><li>Rural deployment</li></ul></div></div><div class="footer-bottom">AgriGuardian X • Startup showcase • Dashboard uses demonstration data.</div></footer>`;
}

function feature(icon,title,text){return `<article class="feature"><div class="feature-icon">${icon}</div><h3>${title}</h3><p>${text}</p></article>`}
function flowDesc(x){return ({Predict:'risk before damage',Search:'drone / field scan',Diagnose:'multimodal AI',Explain:'farmer language',Approve:'human control',Treat:'precision action',Verify:'recovery check',Learn:'Crop Memory',Harvest:'timing & yield',Trust:'Crop Passport'})[x]||''}
function cropCard(c){const cls=c[2]==='High'?'red':c[2]==='Moderate'?'amber':'green'; return `<article class="crop-card"><div style="height:190px;display:grid;place-items:center;font-size:86px;background:linear-gradient(145deg,#eef9f1,#ccefd6)">${c[5]}</div><div class="crop-card-body"><h3>${c[0]} · ${c[1]}</h3><p>${c[4]}. AI combines visual evidence, crop stage, weather, soil and history before recommending action.</p><div class="crop-meta"><span class="tag ${cls}">${c[2]}</span><span class="tag blue">${c[3]} confidence</span></div></div></article>`}

function landing(){
  app.innerHTML = `${topbar()}<main>
    <section class="hero">
      <div><div class="eyebrow"><span class="dot"></span> Rural-first AI • Precision Agriculture • Startup Platform</div><h1>Protect farmer value from <span>seed to sale.</span></h1><p>AgriGuardian X connects crop intelligence, drone + rover inspection, precise farmer-approved intervention, recovery verification, harvest intelligence and buyer-facing traceability into one farm-to-market operating system.</p><div class="hero-actions"><button class="btn btn-primary" onclick="dash('overview')">Explore Full Dashboard</button><a class="btn btn-ghost" href="#platform">See the closed loop</a></div><div class="hero-metrics"><div class="metric"><b>25+</b><span>digital & field modules</span></div><div class="metric"><b>5 crops</b><span>initial intelligence focus</span></div><div class="metric"><b>3 revenue layers</b><span>care • treat • trust</span></div></div></div>
      <div class="scene"><div class="farm-stage"><div class="farm-card" style="display:grid;place-items:center;background:linear-gradient(145deg,#f8fff9,#d8f3df)"><div style="text-align:center;padding:34px"><div style="font-size:110px">🌱</div><h2 style="margin:5px 0;color:#07512d;font-size:36px">AgriGuardian X</h2><p style="color:#4a6858">Search • Diagnose • Decide • Treat • Verify</p></div></div><div class="scan-ring"></div><div class="scan-ring r2"></div><div class="scan-ring r3"></div><div class="floating-panel fp-1"><b>Crop Health 91%</b><span>12 zones monitored</span></div><div class="floating-panel fp-2"><b>AI Alert</b><span>Chilli Zone B • Thrips risk</span></div><div class="floating-panel fp-3"><b>Rover Ready</b><span>Battery 82% • Camera active</span></div></div></div>
    </section>
    <section class="section" id="problem"><div class="section-kicker">The farmer problem</div><h2>A farmer loses value at more than one stage.</h2><p class="section-lead">AgriGuardian X is built around connected losses: weak pre-sowing decisions, late crop observation, unsafe or unnecessary intervention, poor harvest timing, post-harvest deterioration and weak buyer transparency.</p><div class="grid-3">${feature('🌱','Before sowing','Crop suitability, soil context and sowing-window guidance.')}${feature('🐛','During cultivation','Plant-level disease, pest, irrigation, nutrient and weed intelligence.')}${feature('🧪','During treatment','Farmer-approved, measured, targeted intervention.')}${feature('✅','After treatment','Recovery verification and Crop Memory answer: did it work?')}${feature('🌾','At harvest','Maturity, yield estimate, harvest priority and weather-aware harvest window.')}${feature('🔗','At sale','Crop Passport and AgriCollect create buyer trust and group-selling potential.')}</div></section>
    <section class="section" id="platform"><div class="section-kicker">Closed-loop innovation</div><h2>Search → diagnose → explain → act → verify → trust.</h2><p class="section-lead">The same field data is reused across treatment, recovery, harvest and market traceability.</p><div class="workflow">${['Predict','Search','Diagnose','Explain','Approve','Treat','Verify','Learn','Harvest','Trust'].map((x,i)=>`<div class="flow-step"><div class="flow-num">${i+1}</div><b>${x}</b><span>${flowDesc(x)}</span></div>`).join('')}</div></section>
    <section class="section" id="crops"><div class="section-kicker">Crop intelligence</div><h2>Grounded in diseases and pests.</h2><p class="section-lead">Initial focus: tomato, maize, chilli, cotton and groundnut.</p><div class="crop-card-grid">${crops.slice(0,3).map(cropCard).join('')}</div></section>
    <section class="section" id="market"><div class="market-band"><div><div class="section-kicker" style="color:#a9e9bd">Startup model</div><h3>Hardware-enabled service. Platform economics later.</h3><p>AgriGuardian X is designed for FPOs, cooperatives and agricultural service centers so farmers can pay per acre or per service instead of buying a costly autonomous machine individually.</p><button class="btn btn-soft" onclick="dash('market')">Explore AgriMarket 2.0</button></div><div class="market-cards"><div class="market-card"><b>AgriCare</b><span>crop intelligence & monitoring</span></div><div class="market-card"><b>AgriTreat</b><span>precision intervention services</span></div><div class="market-card"><b>AgriTrust</b><span>Crop Passport & buyer tools</span></div><div class="market-card"><b>AgriCollect</b><span>verified farmer group selling</span></div></div></div></section>
  </main>${footer()}`;
  window.scrollTo(0,0);
}

function sidebar(active){return `<aside class="sidebar"><div class="side-title">Farm Intelligence</div>${modules.map(([id,ico,label])=>`<div class="side-item ${id===active?'active':''}" onclick="dash('${id}')"><div class="side-icon">${ico}</div><span>${label}</span></div>`).join('')}</aside>`}
function dash(page='overview'){location.hash=`dashboard/${page}`; app.innerHTML=`${topbar()}<div class="dashboard-shell">${sidebar(page)}<main class="dashboard-main"><div class="page-watermark">AgriGuardian X</div><div class="dash-content">${render(page)}</div></main></div>`; window.scrollTo(0,0)}
function home(){location.hash='';landing()}
function head(title,sub,action=''){return `<div class="dash-head"><div><h1>${title}</h1><p>${sub}</p></div><div style="display:flex;gap:9px;align-items:center">${action}<div class="live-pill"><span class="live-dot"></span> Demo data live</div></div></div>`}
function stats(items){return `<div class="stat-grid">${items.map(x=>`<div class="stat-card"><div class="stat-label">${x[0]}</div><div class="stat-value">${x[1]}</div><div class="stat-note">${x[2]}</div></div>`).join('')}</div>`}
function list(rows){return `<div class="mini-list">${rows.map(r=>`<div class="mini-row"><div><b>${r[0]}</b><span style="display:block">${r[1]}</span></div><span class="tag ${r[2]||'green'}">${r[3]||'OK'}</span></div>`).join('')}</div>`}
function generic(title,sub,items){return `${head(title,sub)}${stats(items)}<div class="panel-grid-2"><section class="panel"><h3>Operational view</h3>${list([['Active zone','Plot A · Row 4','amber','Review'],['System status','All core modules connected','green','Online'],['Next action','Farmer briefing at 17:30','blue','Planned'],['Data sync','Local edge record + cloud mirror','green','Synced']])}</section><section class="panel"><h3>AgriGuardian X logic</h3><p style="color:var(--muted);line-height:1.7">This module is part of the same closed loop. It does not operate as an isolated dashboard widget; its data can feed Crop Memory, treatment decisions, harvest intelligence and crop traceability.</p></section></div>`}

function render(page){
  if(page==='overview') return overview();
  if(page==='disease') return disease();
  if(page==='treatment') return treatment();
  if(page==='market') return market();
  if(page==='collect') return collect();
  if(page==='reports') return reports();
  if(page==='agrisathi') return agrisathi();
  if(page==='alerts') return alerts();
  if(page==='encyclopedia') return `${head('Crop Encyclopedia','Seasonal crop information, disease/pest reference and field guidance.')}<div class="crop-card-grid">${crops.map(cropCard).join('')}</div>`;
  const defs={
    farm:['My Farm','Fields, crops, crop stages and zone-level status.',[['Farm area','12.4 ac','demo farm'],['Active plots','5','all mapped'],['Crops','5','current scope'],['Health','91%','overall']]],
    monitoring:['Live Monitoring','Sensor and field telemetry from connected nodes.',[['Soil moisture','34%','Plot A'],['Humidity','72%','field avg'],['Temperature','29°C','current'],['Nodes online','6/6','connected']]],
    weather:['Weather Intelligence','Weather-aware farm decisions and risk alerts.',[['Rain risk','62%','next 24h'],['Humidity','72%','current'],['Wind','11 km/h','spray check'],['Temp','29°C','current']]],
    'crop-health':['Crop Health','Zone health, severity and field condition.',[['Healthy zones','82%','stable'],['Watch zones','12%','needs review'],['Affected zones','6%','localized'],['Recovery','73%','treated zones']]],
    advisory:['AI Advisory','Predictive farmer actions using crop, soil, weather and history.',[['Open advisories','6','today'],['High priority','2','inspect'],['Preventive','3','next 48h'],['Confidence','90%','avg']]],
    memory:['Crop Memory','Longitudinal plant and zone health history.',[['Tracked zones','48','season'],['Treatment events','19','logged'],['Verified outcomes','15','follow-up'],['History depth','67 days','current season']]],
    irrigation:['Irrigation','Water requirement, moisture zones and control status.',[['Moisture avg','34%','field'],['Pump','Ready','manual approval'],['Zones dry','2','attention'],['Rain delay','1 zone','recommended']]],
    nutrients:['Nutrients & Fertilizer','Crop-stage nutrient guidance and deficiency intelligence.',[['Recommendations','4','active'],['Deficiency flags','2','visual'],['Input records','11','logged'],['Next review','3 days','planned']]],
    weeds:['Weed Intelligence','Crop-vs-weed detection and mapped weed pressure.',[['Weed zones','7','mapped'],['High density','2','priority'],['Coverage','3.8%','estimated'],['Action','Mechanical','preferred']]],
    drone:['Drone Missions','Aerial search, anomaly targeting and geotagging.',[['Missions','4','demo'],['Area scanned','28 ac','total'],['Targets found','9','geotagged'],['Status','Ready','integration mode']]],
    rover:['Rover Control','Mobility, camera, treatment and device status.',[['Battery','82%','AGX-01'],['Mode','Inspection','ready'],['Camera','Active','vision'],['Treatment','Standby','approval required']]],
    harvest:['Harvest Intelligence','Maturity, yield and harvest-window planning.',[['Readiness','63%','farm avg'],['Ready rows','8','priority'],['Est. yield','2.1 t','next 7d'],['Weather window','Good','36 hours']]],
    store:['AgriStore','Post-harvest temperature, humidity, moisture and spoilage monitoring.',[['Storage temp','23°C','stable'],['Humidity','68%','watch'],['Risk','Low','current'],['Batches','3','tracked']]],
    loss:['Crop Loss & Evidence','Before/after evidence and Damage Passport.',[['Damage cases','2','season'],['Mapped area','0.63 ac','latest'],['Evidence','Complete','geo-tagged'],['Passport','Ready','downloadable']]],
    schemes:['Government Schemes','Farmer-support information, reminders and relevant scheme links.',[['Saved topics','4','farmer profile'],['Reminders','2','this month'],['Categories','8','support types'],['Mode','Voice + text','simple summary']]],
    settings:['Settings','Account, devices, access modes and control preferences.',[['Language','Telugu','preferred'],['Farmer Mode','Enabled','simple UI'],['Expert Mode','Enabled','analytics'],['Chemical approval','Required','safety']]]
  };
  const d=defs[page]||defs.farm; return generic(d[0],d[1],d[2]);
}

function overview(){return `${head('Farm Overview','One screen for crop health, field risk, treatment, weather and operations.')}${stats([['Crop health','91%','overall farm'],['Active alerts','6','2 high priority'],['Rover battery','82%','inspection ready'],['Harvest readiness','63%','next 7 days']])}<div class="panel-grid-2"><section class="panel"><h3>AI Predictive Advisory</h3>${list([['Chilli Zone B','Thrips risk increasing','red','High'],['Tomato Row 4','Revisit early-blight zone','amber','Review'],['Plot C irrigation','Rain expected — delay watering','blue','Weather'],['Harvest plan','Tomato rows 1–3 ready soon','green','Ready']])}</section><section class="panel"><h3>Device status</h3>${list([['Rover AGX-01','Battery 82% · camera active','green','Online'],['ESP32 field nodes','6 of 6 connected','green','Online'],['AgriStore node','Monitoring humidity','green','Online'],['Drone layer','Demo mission mode','blue','Demo']])}</section></div><div class="panel-grid-3"><section class="panel"><h3>Field health heatmap</h3><div class="heatmap">${Array.from({length:50},(_,i)=>`<div class="heat ${[8,9,18,27].includes(i)?'bad':[15,16,25,35,36].includes(i)?'warn':'good'}"></div>`).join('')}</div></section><section class="panel"><h3>Today’s farmer briefing</h3>${list([['1. Inspect chilli','Row 6 pest risk','red','Now'],['2. Delay irrigation','Plot C rain risk','blue','Today'],['3. Harvest tomato','Rows 1–3','green','Soon']])}</section><section class="panel"><h3>Startup value loop</h3><p style="color:var(--muted);line-height:1.7">The dashboard links field intelligence to treatment, recovery, harvest and buyer trust instead of stopping at monitoring.</p></section></div>`}

function disease(){return `${head('Disease & Pest AI','Plant-level crop diagnosis with severity, confidence, images and affected zones.')}${stats([['Open cases','5','across 5 crops'],['High severity','1','chilli'],['Average confidence','88%','demo'],['Needs expert review','1','low confidence']])}<div class="crop-card-grid">${crops.map(cropCard).join('')}</div><div class="panel" style="margin-top:16px"><h3>Diagnosis workflow</h3><p style="color:var(--muted);line-height:1.7">Image → crop/stage context → soil/weather/history → confidence check → farmer explanation → treatment recommendation → approval → targeted action → scheduled verification → Crop Memory.</p></div>`}

function treatment(){return `${head('Treatment Center','Farmer-approved precision dosing, action logging and recovery follow-up.',`<button class="btn btn-primary" onclick="toast('Treatment request prepared. Farmer approval is still required.')">Prepare Treatment</button>`)}${stats([['Pending approvals','2','chemical actions'],['Completed','19','season'],['Verified outcomes','15','follow-up'],['Targeted area','6.8%','vs whole field']])}<div class="panel-grid-2"><section class="panel"><h3>Precision treatment queue</h3><table class="data-table"><tr><th>Crop</th><th>Issue</th><th>Zone</th><th>Action</th></tr><tr><td>Chilli</td><td>Thrips pattern</td><td>Row 6</td><td><button class="small-btn primary" onclick="toast('Awaiting farmer approval.')">Approve</button></td></tr><tr><td>Tomato</td><td>Early blight</td><td>Row 4</td><td><button class="small-btn" onclick="toast('Verification scheduled.')">Verify</button></td></tr></table></section><section class="panel"><h3>No-touch dosing logic</h3>${list([['Cartridge','Sealed treatment source','green','Ready'],['Dose control','Measured output','green','Ready'],['Flow feedback','Treatment confirmation','green','Active'],['Safety','Farmer approval required','amber','Required']])}</section></div>`}

function market(){return `${head('AgriMarket 2.0','Buyer-facing crop lifecycle, lot-level trust and seed-to-harvest transparency.',`<button class="btn btn-primary" onclick="toast('Buyer passport link prepared.')">Share Buyer Passport</button>`)}${stats([['Verified lots','14','traceability complete'],['Upcoming harvest','2.1 t','next 7 days'],['Buyer interest','5','demo enquiries'],['Traceability score','94%','record completeness']])}<div class="panel-grid-2"><section class="panel"><h3>Digital Crop Passports</h3><table class="data-table"><tr><th>Lot</th><th>Crop</th><th>Weight</th><th>Grade</th><th>Passport</th></tr><tr><td><b>AGX-TOM-042</b></td><td>Tomato</td><td>286 kg</td><td>A</td><td><button class="small-btn primary" onclick="dash('reports')">View</button></td></tr><tr><td><b>AGX-CHI-018</b></td><td>Chilli</td><td>180 kg</td><td>A/B</td><td><button class="small-btn" onclick="dash('reports')">View</button></td></tr><tr><td><b>AGX-GNT-021</b></td><td>Groundnut</td><td>420 kg</td><td>A</td><td><button class="small-btn" onclick="dash('reports')">View</button></td></tr></table></section><section class="panel"><h3>Buyer trust summary</h3>${list([['Seed/sowing records','Complete','green','Complete'],['Crop health inspections','Complete','green','Complete'],['Treatment records','Complete','green','Complete'],['Recovery evidence','Available','green','Available'],['Harvest quality','Grade A','blue','A']])}</section></div>`}

function collect(){return `${head('AgriCollect','Verified group selling for small farmers and FPO procurement.',`<button class="btn btn-primary" onclick="toast('Compatible farmer lots matched.')">Match Lots</button>`)}${stats([['Matched farmers','4','similar chilli grade'],['Combined quantity','860 kg','buyer-ready total'],['Buyer demand','700 kg','can be fulfilled'],['Shared transport','1 route','planned pickup']])}<section class="panel"><h3>Combined FPO lot</h3><table class="data-table"><tr><th>Farmer</th><th>Lot</th><th>Quantity</th><th>Grade</th><th>Traceability</th></tr>${[['A','CHI-018','180 kg','A'],['B','CHI-019','240 kg','A'],['C','CHI-020','130 kg','A/B'],['D','CHI-021','310 kg','A']].map(x=>`<tr><td><b>Farmer ${x[0]}</b></td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td><td><span class="tag green">Verified</span></td></tr>`).join('')}</table></section>`}

function reports(){return `${head('Reports & Crop Passport','Watermarked farm intelligence reports for farmer, expert and buyer use.',`<button class="btn btn-primary no-print" onclick="window.print()">Print / Save PDF</button>`)}<div class="report-wrap"><article class="crop-report"><div class="report-watermark">AgriGuardian X</div><div class="report-inner"><div class="report-header"><div><div class="report-brand">🌿 AgriGuardian X</div><small>Crop Intelligence & Buyer Traceability Report</small></div><div style="text-align:right"><b>Lot AGX-TOM-042</b><br><small>Generated 22 Aug 2026</small></div></div><h2 class="report-title">Tomato Crop Passport</h2><div class="report-sub">Seed-to-harvest lifecycle summary • Plot A • Demo report</div><div class="report-kpi"><div class="rk"><span>Crop health</span><b>92%</b></div><div class="rk"><span>Traceability</span><b>94%</b></div><div class="rk"><span>Grade A</span><b>72%</b></div><div class="rk"><span>Lot weight</span><b>286 kg</b></div></div><div class="report-section"><h4>Crop lifecycle</h4><p><b>Sowing:</b> 14 June 2026 • <b>Variety:</b> Demo Tomato V1 • <b>Field:</b> Plot A • <b>Monitoring:</b> 28 recorded inspections.</p></div><div class="report-section"><h4>Health & treatment history</h4><ul><li>12 July — early foliar abnormality recorded in Row 4.</li><li>13 July — re-scan confirmed localized early-blight pattern with high confidence.</li><li>Farmer-approved targeted intervention logged for affected plants only.</li><li>18 July — verification showed visible improvement; status changed to improving.</li></ul></div><div class="report-section"><h4>Harvest & quality</h4><p>Maturity model estimated 92% harvest readiness. Visual grading estimated 72% Grade A, 21% Grade B and 7% damaged/other.</p></div><div class="report-note"><b>Traceability note:</b> AgriGuardian X records observed and logged evidence. It does not claim organic, residue-free or chemical-free status without appropriate external verification.</div><div class="signature"><div class="sig-line">Farmer / FPO operator</div><div class="sig-line">AgriGuardian X verified record</div></div></div></article></div>`}

function alerts(){return `${head('Alerts & Notifications','Prioritized alerts across crop health, weather, irrigation, equipment and treatment.')}<div class="mini-list">${[['⚠','Chilli pest risk','Row 6 requires inspection before treatment','red','High'],['🌧','Rain expected','Delay Plot C irrigation and prioritize tomato harvest','amber','Weather'],['✅','Treatment verification complete','Groundnut D3 improved after intervention','green','Verified'],['🔋','Rover battery','82% — no action required','green','System'],['📦','AgriStore humidity rising','Chilli batch requires ventilation check','amber','Storage']].map(x=>`<div class="alert"><div class="alert-icon">${x[0]}</div><div><b>${x[1]}</b><p>${x[2]}</p></div><span class="tag ${x[3]}">${x[4]}</span></div>`).join('')}</div>`}

function agrisathi(){return `${head('AgriSathi','Local-language farmer assistant designed for voice, keypad phones and simple decisions.')}${stats([['Mode','Telugu','demo language'],['Farmer UI','Simple','symbols + voice'],['Keypad support','Planned','SMS / IVR'],['Chemical action','Approval','human in control']])}<div class="panel-grid-2"><section class="panel"><h3>Farmer conversation</h3><div style="display:flex;flex-direction:column;gap:10px"><div style="align-self:flex-end;background:#e6f7ec;padding:12px 14px;border-radius:16px;max-width:75%;font-size:13px">నా పంట ఎలా ఉంది?</div><div style="background:white;border:1px solid var(--line);padding:12px 14px;border-radius:16px;max-width:84%;font-size:13px">మీ పంటలో ఎక్కువ భాగం ఆరోగ్యంగా ఉంది. మిరప Row 6 లో పురుగు సమస్య కనిపించింది.</div><div style="align-self:flex-end;background:#e6f7ec;padding:12px 14px;border-radius:16px;max-width:75%;font-size:13px">మందు వేయాలా?</div><div style="background:white;border:1px solid var(--line);padding:12px 14px;border-radius:16px;max-width:84%;font-size:13px">అవసరమైతే మీ అనుమతి తీసుకుని మాత్రమే చికిత్స ప్రారంభిస్తాను.</div></div></section><section class="panel"><h3>Physical farmer controls</h3>${list([['🟢 Green button','Approve / Yes','green','YES'],['🔴 Red button','Stop / Reject','red','STOP'],['🟡 Yellow button','Repeat / Help','amber','HELP'],['📱 Keypad phone','SMS / IVR','blue','PHONE']])}</section></div>`}

function toast(msg){const old=document.querySelector('.toast');if(old)old.remove();const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2800)}
window.addEventListener('hashchange',route);
function route(){const h=location.hash.replace(/^#/,'');if(h.startsWith('dashboard/'))dash(h.split('/')[1]||'overview');else landing()}
route();
