import {CONDITIONS,recoveryState} from './knowledge.js';
import {extractSignals,classify} from './screening.js';
import {readRecords,saveRecord,clearRecords,plantKey} from './store.js';
import {CATALOG,SOURCES,filterCatalog} from './catalog.js';

const $=id=>document.getElementById(id);let current=null,coords=null,objectUrl=null;
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>show(b.dataset.view));
function show(id){document.querySelectorAll('.view,.nav').forEach(e=>e.classList.remove('active'));$(id).classList.add('active');document.querySelector(`.nav[data-view="${id}"]`).classList.add('active');if(id==='records')renderRecords();if(id==='catalog')renderCatalog()}

$('imageInput').onchange=e=>{const f=e.target.files[0];if(!f)return;if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(f);const img=$('preview');img.src=objectUrl;img.style.display='block';$('dropText').style.display='none';$('analyse').disabled=false;current=null};
$('locate').onclick=()=>{if(!navigator.geolocation){toast('Location is unavailable in this browser.');return}navigator.geolocation.getCurrentPosition(p=>{coords={lat:+p.coords.latitude.toFixed(6),lng:+p.coords.longitude.toFixed(6),accuracy:Math.round(p.coords.accuracy)};$('locationText').textContent=`${coords.lat}, ${coords.lng} (±${coords.accuracy} m)`},e=>toast(e.code===1?'Location permission was not granted.':'Location could not be captured. Enter the field/row/plant identity manually.'),{enableHighAccuracy:true,timeout:8000,maximumAge:30000})};
$('analyse').onclick=async()=>{const f=$('imageInput').files[0];if(!f)return;$('analyse').disabled=true;$('analyse').textContent='Analysing…';try{current=classify(await extractSignals(f));renderResult(current)}catch(e){console.error(e);toast(e.message||'The image could not be analysed.')}finally{$('analyse').disabled=false;$('analyse').textContent='Run visual screening'}};
function renderResult(r){$('empty').hidden=true;$('report').hidden=false;const c=CONDITIONS[r.key];$('condition').textContent=r.abstain?'Uncertain result':c.label;$('scientific').textContent=r.abstain?'Capture another clear tomato leaf image for the supported-class screen.':c.scientific;$('confidence').textContent=Math.round(r.confidence*100)+'%';$('severity').textContent=r.severity;$('quality').textContent=Math.round(r.quality*100)+'%';$('certainty').textContent=r.abstain?'Review needed':'Image-AI screen';$('certainty').classList.toggle('low',r.abstain);$('reasons').replaceChildren(...r.reasons.map(x=>{const li=document.createElement('li');li.textContent=x;return li}));$('recommendation').textContent=r.abstain?'Use a sharp, well-lit image with one leaf filling most of the frame.':c.recommendation;$('caution').textContent=r.abstain?'No condition is saved as certain when quality or confidence is below the safety threshold.':c.caution}
$('save').onclick=()=>{if(!current)return;const record={id:crypto.randomUUID(),field:$('field').value.trim()||'Unspecified',row:$('row').value.trim()||'—',plant:$('plant').value.trim()||'—',observation:$('observation').value,condition:current.abstain?'Uncertain':CONDITIONS[current.key].label,conditionKey:current.key,confidence:Math.round(current.confidence*100),severity:current.severity,coords,createdAt:new Date().toISOString()};const prior=readRecords().find(x=>plantKey(x)===plantKey(record));record.recovery=recoveryState(prior?.severity,record.severity);saveRecord(record);toast(`Saved ${record.field} · Row ${record.row} · Plant ${record.plant}`);show('records')};
function renderRecords(){const rows=readRecords(),groups=new Set(rows.map(plantKey));$('count').textContent=rows.length;$('plants').textContent=groups.size;$('due').textContent=rows.filter(x=>x.recovery==='Baseline'&&x.condition!=='Uncertain').length;$('recordList').innerHTML=rows.length?rows.map(r=>`<article class="record"><div><b>${esc(r.field)} · Row ${esc(r.row)} · Plant ${esc(r.plant)}</b><small>${new Date(r.createdAt).toLocaleString()}</small></div><div><b>${esc(r.condition)}</b><small>${r.confidence}% confidence · ${esc(r.severity)}</small></div><div class="state">${esc(r.recovery)}<small>${r.coords?`${r.coords.lat}, ${r.coords.lng}`:'Manual field identity'}</small></div><span>${esc(r.observation)}</span></article>`).join(''):'<article class="card"><h2>No inspections saved yet</h2><p>Run a screening and save it to create the first plant-level record.</p></article>'}
$('clear').onclick=()=>{clearRecords();renderRecords();toast('Demo records cleared.')};

for(const id of['cropFilter','partFilter'])$(id).onchange=renderCatalog;$('catalogSearch').oninput=renderCatalog;
function renderCatalog(){const rows=filterCatalog({crop:$('cropFilter').value,part:$('partFilter').value,query:$('catalogSearch').value});$('catalogList').innerHTML=`<p class="countline">${rows.length} verified-scope records</p>`+rows.map(x=>`<button class="catalogitem" data-condition="${x.id}"><span><b>${esc(x.crop)} · ${esc(x.name)}</b><small>${esc(x.parts.join(' · '))}</small></span><span class="type">${esc(x.type)}</span></button>`).join('');document.querySelectorAll('.catalogitem').forEach(b=>b.onclick=()=>renderCatalogDetail(b.dataset.condition,b))}
function renderCatalogDetail(id,button){document.querySelectorAll('.catalogitem').forEach(x=>x.classList.remove('active'));button.classList.add('active');const x=CATALOG.find(r=>r.id===id),s=SOURCES[x.source];$('catalogDetail').innerHTML=`<span class="eyebrow">${esc(x.type)} · ${esc(x.crop)}</span><h2>${esc(x.name)}</h2><p><b>Affected parts:</b> ${esc(x.parts.join(', '))}</p><h3>Visible pattern</h3><ul>${x.symptoms.map(v=>`<li>${esc(v)}</li>`).join('')}</ul><h3>How to confirm</h3><p>${esc(x.confirm)}</p><h3>Farmer next steps</h3><ol>${x.actions.map(v=>`<li>${esc(v)}</li>`).join('')}</ol><p class="caution">Exact product and quantity depend on crop stage, field area, product label, local registration and expert guidance. The system does not invent a dose.</p><a class="source" href="${s.url}" target="_blank" rel="noopener noreferrer">Source: ${esc(s.name)}</a>`}
CATALOG.forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=`${x.crop} · ${x.name}`;$('treatCondition').append(o)});
$('calculateDose').onclick=()=>{const area=Number($('treatArea').value),rate=Number($('labelRate').value),unit=$('rateUnit').value,ref=$('labelReference').value.trim(),condition=CATALOG.find(x=>x.id===$('treatCondition').value);if(!Number.isFinite(area)||area<=0||area>10000||!Number.isFinite(rate)||rate<=0||rate>100000||!ref||!condition){toast('Enter a valid area, verified label rate and its reference.');return}const total=+(area*rate).toFixed(3);$('doseResult').innerHTML=`<span class="eyebrow">LABEL-BASED CALCULATION</span><h2>${esc(condition.crop)} · ${esc(condition.name)}</h2><div class="dose">${total} ${esc(unit)}</div><p>${area} acre × ${rate} ${esc(unit)}/acre. Reference: ${esc(ref)}.</p><div class="checklist"><div class="check"><b>1. Confirm</b><span>Verify the condition, crop stage, local registration, label rate, protective equipment and weather.</span></div><div class="check"><b>2. Target</b><span>Treat only the confirmed area. Keep farmer approval and an application record.</span></div><div class="check"><b>3. Revisit</b><span>Return to the same row and plant/zone, capture a comparable image and mark improving, stable or worsening.</span></div></div><p class="caution">This arithmetic does not replace the product label or local agricultural advice. Do not mix products unless the label expressly permits it.</p>`};
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(m){const t=$('toast');t.textContent=m;t.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>t.hidden=true,3000)}
