import{CONDITIONS,recoveryState}from'./knowledge.js';import{extractSignals,classify}from'./screening.js';import{readRecords,saveRecord,clearRecords,plantKey}from'./store.js';
const $=id=>document.getElementById(id);let current=null,coords=null;
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>show(b.dataset.view));
function show(id){document.querySelectorAll('.view,.nav').forEach(e=>e.classList.remove('active'));$(id).classList.add('active');document.querySelector(`.nav[data-view="${id}"]`).classList.add('active');if(id==='records')renderRecords()}
$('imageInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const img=$('preview');img.src=URL.createObjectURL(f);img.style.display='block';$('dropText').style.display='none';$('analyse').disabled=false;current=null};
$('locate').onclick=()=>{if(!navigator.geolocation){toast('Location is unavailable in this browser.');return}navigator.geolocation.getCurrentPosition(p=>{coords={lat:+p.coords.latitude.toFixed(6),lng:+p.coords.longitude.toFixed(6),accuracy:Math.round(p.coords.accuracy)};$('locationText').textContent=`${coords.lat}, ${coords.lng} (±${coords.accuracy} m)`},()=>toast('Location permission was not granted.'),{enableHighAccuracy:true,timeout:8000})};
$('analyse').onclick=async()=>{const f=$('imageInput').files[0];$('analyse').disabled=true;$('analyse').textContent='Analysing…';try{const signals=await extractSignals(f);current=classify(signals);renderResult(current)}catch(e){toast(e.message)}finally{$('analyse').disabled=false;$('analyse').textContent='Run visual screening'}};
function renderResult(r){$('empty').hidden=true;$('report').hidden=false;const c=CONDITIONS[r.key];$('condition').textContent=r.abstain?'Uncertain result':c.label;$('scientific').textContent=r.abstain?'Capture another clear leaf image for a supported-class screen.':c.scientific;$('confidence').textContent=Math.round(r.confidence*100)+'%';$('severity').textContent=r.severity;$('quality').textContent=Math.round(r.quality*100)+'%';$('certainty').textContent=r.abstain?'Review needed':'Prototype screen';$('certainty').classList.toggle('low',r.abstain);$('reasons').innerHTML=r.reasons.map(x=>`<li>${x}</li>`).join('');$('recommendation').textContent=r.abstain?'Use a sharp, well-lit image with one leaf filling most of the frame.':c.recommendation;$('caution').textContent=r.abstain?'No condition is saved as certain when quality or confidence is below the safety threshold.':c.caution}
$('save').onclick=()=>{if(!current)return;const record={id:crypto.randomUUID(),field:$('field').value.trim()||'Unspecified',row:$('row').value.trim()||'—',plant:$('plant').value.trim()||'—',observation:$('observation').value,condition:current.abstain?'Uncertain':CONDITIONS[current.key].label,conditionKey:current.key,confidence:Math.round(current.confidence*100),severity:current.severity,coords,createdAt:new Date().toISOString()};const prior=readRecords().find(x=>plantKey(x)===plantKey(record));record.recovery=recoveryState(prior?.severity,record.severity);saveRecord(record);toast(`Saved ${record.field} · Row ${record.row} · Plant ${record.plant}`);show('records')};
function renderRecords(){const rows=readRecords(),groups=new Set(rows.map(plantKey));$('count').textContent=rows.length;$('plants').textContent=groups.size;$('due').textContent=rows.filter(x=>x.recovery==='Baseline'&&x.condition!=='Uncertain').length;$('recordList').innerHTML=rows.length?rows.map(r=>`<article class="record"><div><b>${escapeHtml(r.field)} · Row ${escapeHtml(r.row)} · Plant ${escapeHtml(r.plant)}</b><small>${new Date(r.createdAt).toLocaleString()}</small></div><div><b>${escapeHtml(r.condition)}</b><small>${r.confidence}% confidence · ${r.severity}</small></div><div class="state">${r.recovery}<small>${r.coords?`${r.coords.lat}, ${r.coords.lng}`:'Manual field identity'}</small></div><span>${r.observation}</span></article>`).join(''):'<article class="card"><h2>No inspections saved yet</h2><p>Run a screening and save it to create the first plant-level record.</p></article>'}
$('clear').onclick=()=>{clearRecords();renderRecords();toast('Demo records cleared.')};function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function toast(m){const t=$('toast');t.textContent=m;t.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>t.hidden=true,2600)}
