import {CONDITIONS,recoveryState} from './knowledge.js';
import {extractSignals,classify} from './screening.js';
import {readRecords,saveRecord,clearRecords,plantKey} from './store.js';
import {CATALOG,SOURCES,filterCatalog} from './catalog.js';
import {getGuidance,revisitText,speechText} from './farmerGuidance.js';
import {treatmentFor} from './treatmentRecommendations.js';

const $=id=>document.getElementById(id);
let current=null,coords=null,objectUrl=null,farmerDecision=null;

document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>show(b.dataset.view));
function show(id){document.querySelectorAll('.view,.nav').forEach(e=>e.classList.remove('active'));$(id).classList.add('active');document.querySelector(`.nav[data-view="${id}"]`).classList.add('active');if(id==='records')renderRecords();if(id==='catalog')renderCatalog();if(id==='treatment')renderTreatmentPlan()}

$('imageInput').onchange=e=>{const f=e.target.files[0];if(!f)return;if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(f);$('preview').src=objectUrl;$('preview').style.display='block';$('dropText').style.display='none';$('analyse').disabled=false;current=null;farmerDecision=null;$('save').disabled=true};
$('locate').onclick=()=>{if(!navigator.geolocation){toast('Location is unavailable in this browser.');return}navigator.geolocation.getCurrentPosition(p=>{coords={lat:+p.coords.latitude.toFixed(6),lng:+p.coords.longitude.toFixed(6),accuracy:Math.round(p.coords.accuracy)};$('locationText').textContent=`${coords.lat}, ${coords.lng} (±${coords.accuracy} m)`},e=>toast(e.code===1?'Location permission was not granted.':'Location could not be captured. Enter the field, row and plant identity manually.'),{enableHighAccuracy:true,timeout:8000,maximumAge:30000})};
$('analyse').onclick=async()=>{const f=$('imageInput').files[0];if(!f)return;$('analyse').disabled=true;$('analyse').textContent='Analysing plant…';try{current=classify(await extractSignals(f));farmerDecision=null;renderResult(current)}catch(e){console.error(e);toast(e.message||'The image could not be analysed.')}finally{$('analyse').disabled=false;$('analyse').textContent='Analyse plant image'}};

function renderResult(r){$('empty').hidden=true;$('report').hidden=false;const c=CONDITIONS[r.key];$('condition').textContent=r.abstain?'Uncertain result':c.label;$('scientific').textContent=r.abstain?'Capture another clear tomato leaf image for the supported-class screen.':c.scientific;$('confidence').textContent=Math.round(r.confidence*100)+'%';$('severity').textContent=r.severity;$('quality').textContent=Math.round(r.quality*100)+'%';$('certainty').textContent=r.abstain?'Review needed':'Supported AI class';$('certainty').classList.toggle('low',r.abstain);$('save').disabled=true;$('decisionStatus').textContent='';r.abstain?renderUncertainGuidance():renderFarmerGuidance();$('report').scrollIntoView({behavior:'smooth',block:'start'})}
function renderSteps(id,items){$(id).replaceChildren(...items.map((x,i)=>{const d=document.createElement('div');d.className='guidance-step';d.innerHTML=`<b>${String(i+1).padStart(2,'0')}</b><p></p>`;d.querySelector('p').textContent=x;return d}))}
function plantIdentity(){const f=$('field').value.trim()||'Unspecified',r=$('row').value.trim()||'—',p=$('plant').value.trim()||'—';return `Plant identity: ${f} → Row ${r} → Plant/zone ${p}`}
function renderUncertainGuidance(){const msg='A reliable treatment plan should not be generated from this image. Capture one clear leaf in good light and scan again.';$('guideTitle').textContent='A clearer image is needed before treatment guidance';$('guideMeaning').textContent=msg;$('guideSeriousness').textContent='AI confidence or image quality is below the safety threshold, so AgriGuardian X is refusing to force a diagnosis.';renderSteps('guideNow',['Fill most of the frame with one leaf.','Use good natural light and keep the camera steady.','Avoid blur, shadows and multiple overlapping leaves.']);$('guideField').textContent=msg;$('guideBio').textContent='No biological treatment is recommended from an uncertain scan.';$('guideChemical').textContent='No chemical treatment is recommended from an uncertain scan.';$('guideApply').textContent='Confirm the crop condition before applying any treatment.';renderSteps('guideAvoid',['Do not spray based on an uncertain result.','Do not treat the AI result as a laboratory or expert confirmation.']);renderSteps('guidePrevention',['Observe the plant carefully and capture a new clear image for comparison.']);$('guideWhy').textContent='For safety, the system abstains instead of forcing a disease label when the visual evidence is not strong enough.';$('guideSource').removeAttribute('href');$('guideSource').textContent='A verified source will appear after a supported diagnosis';$('guideRevisit').textContent='Repeat the scan with a clearer image first.';$('guidePlantId').textContent=plantIdentity();$('approvePlan').disabled=true}
function renderFarmerGuidance(){if(!current||current.abstain)return;const g=getGuidance(current.key,'en');$('guideTitle').textContent=g.title;$('guideMeaning').textContent=g.meaning;$('guideSeriousness').textContent=`${current.severity}: ${g.seriousness}`;renderSteps('guideNow',g.now);$('guideField').textContent=g.field;$('guideBio').textContent=g.bio;$('guideChemical').textContent=g.chemical;$('guideApply').textContent=g.apply;renderSteps('guideAvoid',g.avoid);renderSteps('guidePrevention',g.prevention);$('guideWhy').textContent=`The AI screened this image with ${Math.round(current.confidence*100)}% confidence among its supported tomato classes. Treatment information is linked to a verified agricultural source; the AI does not invent a pesticide or dose.`;$('guideSource').href=g.source.url;$('guideSource').textContent=`Verified source: ${g.source.name}`;$('guideRevisit').textContent=revisitText(current.key,'en');$('guidePlantId').textContent=plantIdentity();$('approvePlan').disabled=false}

$('listen').onclick=()=>{if(!current||current.abstain){toast('A supported diagnosis is needed before voice guidance.');return}if(!('speechSynthesis' in window)){toast('Voice playback is unavailable in this browser.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(speechText(current.key,'en'));u.lang='en-IN';u.rate=.9;speechSynthesis.speak(u)};
$('approvePlan').onclick=()=>setDecision('approved');
$('expertHelp').onclick=()=>setDecision('expert');
$('reviewOptions').onclick=()=>{setDecision('review');show('catalog')};
function setDecision(decision){farmerDecision=decision;const messages={approved:'Guidance approved. You can now save this plant record and its revisit plan.',expert:'Expert review requested. Save the plant record so the case remains traceable.',review:'Opening the verified crop-health library for additional options.'};$('decisionStatus').textContent=messages[decision];$('save').disabled=!current||current.abstain||!['approved','expert'].includes(decision)}

$('save').onclick=()=>{if(!current||current.abstain||!farmerDecision)return;const g=getGuidance(current.key,'en'),record={id:crypto.randomUUID(),field:$('field').value.trim()||'Unspecified',row:$('row').value.trim()||'—',plant:$('plant').value.trim()||'—',observation:$('observation').value,condition:CONDITIONS[current.key].label,conditionKey:current.key,confidence:Math.round(current.confidence*100),severity:current.severity,coords,farmerDecision,guidanceSource:g.source.name,revisitMinDays:g.revisit[0],revisitMaxDays:g.revisit[1],createdAt:new Date().toISOString()};const prior=readRecords().find(x=>plantKey(x)===plantKey(record));record.recovery=recoveryState(prior?.severity,record.severity);saveRecord(record);toast(`Saved ${record.field} · Row ${record.row} · Plant ${record.plant}`);show('records')};
function renderRecords(){const rows=readRecords(),groups=new Set(rows.map(plantKey));$('count').textContent=rows.length;$('plants').textContent=groups.size;$('due').textContent=rows.filter(x=>x.recovery==='Baseline'&&x.condition!=='Uncertain').length;$('recordList').innerHTML=rows.length?rows.map(r=>`<article class="record"><div><b>${esc(r.field)} · Row ${esc(r.row)} · Plant ${esc(r.plant)}</b><small>${new Date(r.createdAt).toLocaleString()}</small></div><div><b>${esc(r.condition)}</b><small>${r.confidence}% confidence · ${esc(r.severity)}</small></div><div class="state">${esc(r.recovery)}<small>${r.coords?`${r.coords.lat}, ${r.coords.lng}`:'Manual field identity'}</small></div><span>${r.farmerDecision==='approved'?'Guidance approved':r.farmerDecision==='expert'?'Expert help requested':'Recorded'}${r.revisitMinDays?` · revisit ${r.revisitMinDays}–${r.revisitMaxDays}d`:''}</span></article>`).join(''):'<article class="card"><h2>No inspections saved yet</h2><p>Run a screening, review the guidance and save it to create the first plant-level crop-health record.</p></article>'}
$('clear').onclick=()=>{clearRecords();renderRecords();toast('Demo records cleared.')};

for(const id of['cropFilter','partFilter'])$(id).onchange=renderCatalog;$('catalogSearch').oninput=renderCatalog;
function renderCatalog(){const rows=filterCatalog({crop:$('cropFilter').value,part:$('partFilter').value,query:$('catalogSearch').value});$('catalogList').innerHTML=`<p class="countline">${rows.length} verified-scope records</p>`+rows.map(x=>`<button class="catalogitem" data-condition="${x.id}"><span><b>${esc(x.crop)} · ${esc(x.name)}</b><small>${esc(x.parts.join(' · '))}</small></span><span class="type">${esc(x.type)}</span></button>`).join('');document.querySelectorAll('.catalogitem').forEach(b=>b.onclick=()=>renderCatalogDetail(b.dataset.condition,b))}
function renderCatalogDetail(id,button){document.querySelectorAll('.catalogitem').forEach(x=>x.classList.remove('active'));button.classList.add('active');const x=CATALOG.find(r=>r.id===id),s=SOURCES[x.source];$('catalogDetail').innerHTML=`<span class="eyebrow">${esc(x.type)} · ${esc(x.crop)}</span><h2>${esc(x.name)}</h2><p><b>Affected parts:</b> ${esc(x.parts.join(', '))}</p><h3>Visible pattern</h3><ul>${x.symptoms.map(v=>`<li>${esc(v)}</li>`).join('')}</ul><h3>How to confirm</h3><p>${esc(x.confirm)}</p><h3>Farmer next steps</h3><ol>${x.actions.map(v=>`<li>${esc(v)}</li>`).join('')}</ol><p class="caution">Exact product and quantity depend on crop stage, field area, product label, local registration and expert guidance. The system does not invent a dose.</p><a class="source" href="${s.url}" target="_blank" rel="noopener noreferrer">Source: ${esc(s.name)}</a>`}
CATALOG.forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=`${x.crop} · ${x.name}`;$('treatCondition').append(o)});
$('treatCondition').onchange=renderTreatmentPlan;
function renderTreatmentPlan(){const condition=CATALOG.find(x=>x.id===$('treatCondition').value);const plan=treatmentFor(condition?.id);if(!condition)return;if(!plan){$('doseResult').innerHTML=`<span class="eyebrow">VERIFIED TREATMENT GUIDANCE</span><h2>${esc(condition.crop)} · ${esc(condition.name)}</h2><p>This condition is available in the inspection library, but a locally verified product recommendation has not been loaded into the treatment module yet.</p><div class="checklist"><div class="check"><b>What to do now</b><span>${esc(condition.actions.join(' • '))}</span></div><div class="check"><b>Product decision</b><span>Use only a locally registered product or fertilizer recommendation confirmed by an official agricultural source or qualified expert.</span></div></div><p class="caution">AgriGuardian X will not invent a product, fertilizer or dose when the verified treatment record is missing.</p>`;return}
$('doseResult').innerHTML=`<span class="eyebrow">WHAT SHOULD I USE?</span><h2>${esc(plan.title)}</h2><p class="caution">${esc(plan.diagnosisNote)}</p><h3>Do this first</h3><div class="checklist">${plan.immediate.map((x,i)=>`<div class="check"><b>${i+1}. Action</b><span>${esc(x)}</span></div>`).join('')}</div><h3>Disease-control options</h3><div class="checklist">${plan.chemical.map(x=>`<div class="check"><b>${esc(x.name)}</b><span><strong>${esc(x.rate)}</strong><br>${esc(x.note)}</span></div>`).join('')}</div><h3>${esc(plan.nutrition.title)}</h3><div class="checklist">${plan.nutrition.items.map(x=>`<div class="check"><span>${esc(x)}</span></div>`).join('')}</div><p class="caution">${esc(plan.nutrition.caution)}</p><a class="source" href="${plan.source.url}" target="_blank" rel="noopener noreferrer">Verified source: ${esc(plan.source.name)}</a><p class="privacy">${esc(plan.calculatorHint)}</p>`}
renderTreatmentPlan();
$('calculateDose').onclick=()=>{const area=Number($('treatArea').value),rate=Number($('labelRate').value),unit=$('rateUnit').value,ref=$('labelReference').value.trim(),condition=CATALOG.find(x=>x.id===$('treatCondition').value);if(!Number.isFinite(area)||area<=0||area>10000||!Number.isFinite(rate)||rate<=0||rate>100000||!ref||!condition){toast('Enter a valid area, verified label rate and its reference.');return}const total=+(area*rate).toFixed(3),plan=treatmentFor(condition.id);$('doseResult').innerHTML=`<span class="eyebrow">LABEL-BASED QUANTITY</span><h2>${esc(condition.crop)} · ${esc(condition.name)}</h2>${plan?`<p><b>Selected treatment guidance:</b> ${esc(plan.chemical[0].name)} — ${esc(plan.chemical[0].rate)}</p>`:''}<div class="dose">${total} ${esc(unit)}</div><p>${area} acre × ${rate} ${esc(unit)}/acre. Reference: ${esc(ref)}.</p><div class="checklist"><div class="check"><b>1. Confirm product</b><span>Make sure the product is registered for this crop and condition and that the rate matches its current label.</span></div><div class="check"><b>2. Treat only confirmed area</b><span>Do not automatically spray the full field if the disease is confined to a smaller zone.</span></div><div class="check"><b>3. Revisit</b><span>Return to the same row and plant/zone, capture a comparable image and mark improving, stable or worsening.</span></div></div><p class="caution">The calculator converts a verified label rate to your treated area. It does not override the product label or local agricultural advice.</p>`};
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(m){const t=$('toast');t.textContent=m;t.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>t.hidden=true,3200)}