export const SOURCES={
 tnauTomato:{name:'TNAU Agritech Portal — Tomato diseases',url:'https://agritech.tnau.ac.in/crop_protection/crop_prot_crop%20diseases_veg_tomato.html'},
 tnauCrops:{name:'TNAU Agritech Portal — Crop protection',url:'https://agritech.tnau.ac.in/crop_protection/crop_protection.html'},
 ppqs:{name:'Government of India PPQS — IPM packages',url:'https://ppqs.gov.in/ipm-packages'},
 plantVillage:{name:'PlantVillage image dataset',url:'https://github.com/spMohanty/PlantVillage-Dataset'}
};
const c=(id,crop,name,type,parts,symptoms,confirm,actions,source='tnauCrops')=>({id,crop,name,type,parts,symptoms,confirm,actions,source});
export const CATALOG=[
 c('tom-early','Tomato','Early blight','Disease',['leaf','stem','fruit'],['Brown target-like rings, usually first on older leaves','Yellow tissue around expanding lesions'],'Check concentric rings and whether older foliage is affected first.',['Remove infected crop debris','Improve airflow and avoid prolonged leaf wetness','Use only a locally registered treatment after expert confirmation'],'tnauTomato'),
 c('tom-late','Tomato','Late blight','Disease',['leaf','stem','fruit'],['Rapidly expanding water-soaked brown lesions','Pale growth near lesion edge in humid weather'],'Inspect leaf undersides early morning and consider recent cool, humid weather.',['Separate the affected zone','Avoid moving wet foliage between rows','Seek urgent local plant-pathology guidance'],'tnauTomato'),
 c('tom-wilt','Tomato','Wilt complex','Disease',['root','stem','whole plant'],['Sudden or progressive wilting','Brown vascular tissue may be visible inside stem'],'Use a clean stem check with expert guidance and confirm in a lab where possible.',['Mark affected plants','Do not move contaminated soil or tools','Use rotation and locally recommended sanitation'],'tnauTomato'),
 c('tom-curl','Tomato','Leaf curl complex','Disease',['leaf','whole plant'],['Upward curling and reduced leaf size','Stunting; whiteflies may be present'],'Inspect new growth and vector pressure; rule out herbicide and nutrient stress.',['Control vectors using IPM','Remove severe sources under local guidance','Use healthy planting material'],'ppqs'),
 c('tom-borer','Tomato','Fruit borer','Pest',['flower','fruit'],['Entry holes with frass','Larva feeding inside fruit'],'Inspect damaged fruit and nearby flowers for larvae or eggs.',['Collect damaged fruits','Use pheromone monitoring where recommended','Act only after threshold-based scouting'],'ppqs'),
 c('chi-anth','Chilli','Anthracnose / fruit rot','Disease',['fruit','stem'],['Dark sunken fruit lesions','Orange or pink spore masses in humidity'],'Check whether lesions are sunken and expanding on mature fruit.',['Remove infected fruit','Reduce splash and injury','Use clean seed and local guidance'],'tnauCrops'),
 c('chi-curl','Chilli','Leaf curl complex','Disease',['leaf','whole plant'],['Curling, puckering and shortened internodes','Stunting with possible vector insects'],'Inspect new leaves and scout whiteflies, thrips and mites.',['Manage vectors with IPM','Remove alternate weed hosts','Use tolerant material where recommended'],'ppqs'),
 c('chi-thrips','Chilli','Thrips injury','Pest',['leaf','flower','fruit'],['Silvery scraping and upward curling','Tiny insects in flowers or leaf folds'],'Tap flowers over white paper and inspect with magnification.',['Monitor natural enemies','Remove weed hosts','Use controls only after threshold confirmation'],'ppqs'),
 c('chi-mite','Chilli','Broad mite injury','Pest',['leaf','bud'],['Downward curling and hardened narrow leaves','Bronzed tender growth'],'Inspect tender growth with magnification and rule out virus.',['Avoid unnecessary broad-spectrum sprays','Conserve natural enemies','Use registered control only after confirmation'],'ppqs'),
 c('mai-faw','Maize','Fall armyworm','Pest',['leaf','whorl','cob'],['Window-pane feeding and ragged whorl damage','Fresh frass deep in the whorl'],'Inspect the whorl for larvae and record affected plants per sample.',['Scout from early crop stage','Conserve natural enemies','Follow official threshold-based whorl management'],'ppqs'),
 c('mai-tlb','Maize','Turcicum leaf blight','Disease',['leaf'],['Long cigar-shaped grey-green lesions','Lesions merge and dry large areas'],'Check lesion shape and crop stage; distinguish from other blights.',['Use resistant hybrids where suitable','Manage infected residue','Seek treatment advice only if economically justified'],'tnauCrops'),
 c('mai-stem','Maize','Stem borer','Pest',['leaf','stem','whorl'],['Pin holes on emerging leaves','Dead heart or stem tunnelling'],'Inspect whorl and split a damaged stem for larvae or frass.',['Scout early stages','Manage infested residue after harvest','Use official threshold-based IPM'],'ppqs'),
 c('mai-zinc','Maize','Suspected zinc deficiency','Nutrient stress',['leaf'],['Broad pale bands beside the midrib','Young plants may be stunted'],'Confirm with soil or tissue testing and rule out root damage.',['Request a soil/tissue test','Correct pH or nutrient source from test','Calculate dose only from area, test and product analysis'],'tnauCrops'),
 c('cot-pink','Cotton','Pink bollworm','Pest',['flower','boll','seed'],['Rosette flowers or internal boll feeding','Poor boll opening and damaged seed'],'Open sampled bolls and use trap/scouting records.',['Destroy residues as directed','Use timely harvest and resistance management','Act only from threshold-based advice'],'ppqs'),
 c('cot-suck','Cotton','Sucking-pest complex','Pest',['leaf','bud'],['Leaf curling, yellowing or honeydew','Aphids, jassids, whiteflies or thrips underneath'],'Identify species and count per leaf before choosing control.',['Conserve natural enemies','Avoid unnecessary broad-spectrum sprays','Use official economic thresholds'],'ppqs'),
 c('cot-blight','Cotton','Bacterial blight','Disease',['leaf','stem','boll'],['Angular water-soaked leaf spots','Black arm lesions or boll spotting'],'Look for angular lesions limited by veins and inspect stems.',['Use clean seed and resistant varieties','Avoid working wet crops','Manage residue locally'],'tnauCrops'),
 c('cot-wilt','Cotton','Fusarium wilt','Disease',['root','stem','whole plant'],['Yellowing and progressive wilt','Brown vascular discoloration'],'Check lower-stem vascular browning and nematode interaction.',['Map affected patches','Use rotation and resistant varieties','Improve soil health with local advice'],'tnauCrops'),
 c('gnt-els','Groundnut','Early leaf spot','Disease',['leaf','petiole','stem'],['Brown spots often with yellow halo','Defoliation as disease advances'],'Check both leaf surfaces and compare with late leaf spot.',['Manage volunteer hosts and residue','Improve canopy airflow','Follow integrated disease guidance'],'tnauCrops'),
 c('gnt-lls','Groundnut','Late leaf spot','Disease',['leaf','petiole','stem'],['Dark brown to black spots','Severe defoliation'],'Inspect lower leaf surface and distinguish from rust.',['Scout after canopy closure','Use resistant varieties','Use local disease program after confirmation'],'tnauCrops'),
 c('gnt-rust','Groundnut','Rust','Disease',['leaf'],['Orange-brown pustules below leaves','Yellowing and premature leaf fall'],'Inspect raised pustules with magnification.',['Remove volunteer plants','Monitor spread in humid weather','Seek registered management advice'],'tnauCrops'),
 c('gnt-collar','Groundnut','Collar/root rot','Disease',['root','collar','seedling'],['Seedling collapse and dark collar lesion','Root or collar decay'],'Inspect collar and roots and map drainage relationship.',['Improve drainage','Use healthy treated seed under official guidance','Avoid moving contaminated soil'],'tnauCrops'),
 c('gnt-miner','Groundnut','Leaf miner','Pest',['leaf'],['Serpentine mines or folded leaflets','Larva within mined tissue'],'Open a fresh mine and sample affected leaflets.',['Conserve parasitoids','Remove alternate hosts where appropriate','Use threshold-based management'],'ppqs')
];
export function filterCatalog({crop='All',part='All',query=''}){const q=query.trim().toLowerCase();return CATALOG.filter(x=>(crop==='All'||x.crop===crop)&&(part==='All'||x.parts.includes(part))&&(!q||[x.name,x.type,...x.symptoms,...x.parts].join(' ').toLowerCase().includes(q)))}
