export const FARMER_GUIDANCE={
  healthy:{
    source:{name:'TNAU Agritech Portal — Tomato crop protection',url:'https://agritech.tnau.ac.in/crop_protection/crop_prot_crop%20diseases_veg_tomato.html'},
    revisit:[7,10],
    en:{title:'Your tomato leaf does not show a supported disease pattern',meaning:'The current image looks closest to the healthy class among the three AI-supported tomato classes. Continue monitoring because this screen does not rule out every disease, pest or nutrient problem.',seriousness:'No supported disease signal was found in this image.',now:['Keep the plant under normal observation.','Check new leaves and nearby plants during routine field inspection.','Capture another image if spots, curling, wilting or unusual colour appears.'],field:'Continue normal field hygiene, irrigation and scouting practices suitable for the crop stage.',bio:'No biological treatment is suggested from this healthy-class screen.',chemical:'Do not apply a pesticide only because an AI scan was performed. Use crop-protection products only for a confirmed need and according to verified local guidance.',apply:'No treatment application is required from this result.',avoid:['Do not spray preventively without a confirmed need.','Do not treat this result as proof that every possible crop problem is absent.'],prevention:['Inspect plants regularly.','Keep field records so new symptoms can be compared with earlier observations.','Use clean planting material and locally recommended crop-management practices.']},
    te:{title:'మీ టమాటా ఆకులో ప్రస్తుతం మద్దతు ఉన్న వ్యాధి లక్షణం కనిపించలేదు',meaning:'ఈ చిత్రం ప్రస్తుతం AI మద్దతు ఉన్న మూడు టమాటా తరగతుల్లో ఆరోగ్యమైన ఆకుకు దగ్గరగా ఉంది. అయితే ప్రతి వ్యాధి, పురుగు లేదా పోషక లోపాన్ని ఈ స్కాన్ పూర్తిగా నిరాకరించదు కాబట్టి మొక్కను పర్యవేక్షించండి.',seriousness:'ఈ చిత్రంలో మద్దతు ఉన్న వ్యాధి సంకేతం కనిపించలేదు.',now:['మొక్కను సాధారణంగా గమనిస్తూ ఉండండి.','కొత్త ఆకులు మరియు పక్కనున్న మొక్కలను క్రమం తప్పకుండా పరిశీలించండి.','మచ్చలు, ముడతలు, వాడిపోవడం లేదా అసాధారణ రంగు కనిపిస్తే కొత్త ఫోటో తీయండి.'],field:'పంట దశకు సరిపోయే సాధారణ పరిశుభ్రత, నీటిపారుదల మరియు పర్యవేక్షణ కొనసాగించండి.',bio:'ఈ ఆరోగ్య ఫలితంపై బయాలాజికల్ ట్రీట్మెంట్ అవసరమని సిస్టమ్ సూచించడం లేదు.',chemical:'AI స్కాన్ చేశామని మాత్రమే పురుగుమందు వాడకండి. ధృవీకరించిన అవసరం ఉన్నప్పుడు మాత్రమే స్థానిక అధికారిక సూచనల ప్రకారం ఉపయోగించండి.',apply:'ఈ ఫలితం ఆధారంగా ఎలాంటి చికిత్స అప్లికేషన్ అవసరం లేదు.',avoid:['అవసరం నిర్ధారించకుండా ముందస్తుగా స్ప్రే చేయకండి.','ఈ ఫలితం అన్ని రకాల పంట సమస్యలు లేవని పూర్తి నిర్ధారణగా భావించకండి.'],prevention:['మొక్కలను క్రమం తప్పకుండా పరిశీలించండి.','కొత్త లక్షణాలను పాత రికార్డులతో పోల్చేందుకు ఫీల్డ్ రికార్డు ఉంచండి.','శుభ్రమైన నాటే పదార్థం మరియు స్థానికంగా సిఫారసు చేసిన పద్ధతులు పాటించండి.']}
  },
  early:{
    source:{name:'TNAU Agritech Portal — Tomato diseases',url:'https://agritech.tnau.ac.in/crop_protection/crop_prot_crop%20diseases_veg_tomato.html'},
    revisit:[3,5],
    en:{title:'Your tomato leaf shows a pattern consistent with suspected Early Blight',meaning:'Early blight commonly begins on older leaves as brown lesions that may develop target-like rings. If symptoms expand, damaged foliage can reduce healthy plant growth. This is an AI screening result, so important treatment decisions should still be confirmed.',seriousness:'Act early, especially when lesions are increasing or several nearby plants show the same pattern.',now:['Inspect older leaves for expanding brown spots with concentric rings.','Remove heavily affected plant debris according to local crop guidance and keep it away from healthy plants.','Check nearby tomato plants in the same row or zone for similar symptoms.','Reduce prolonged leaf wetness where practical and avoid unnecessary movement through wet foliage.'],field:'Prioritise field sanitation, removal of heavily affected debris, regular scouting and practices that reduce prolonged leaf wetness and improve airflow where appropriate.',bio:'Use a biological option only when it is specifically recommended for tomato early blight by a verified local agricultural source or qualified expert.',chemical:'Use a chemical option only after confirming the condition and only from a locally registered product label or qualified agricultural recommendation. AgriGuardian X does not invent a pesticide, concentration or dose.',apply:'Treat only the confirmed plant or affected zone when the verified recommendation allows targeted action. Follow the registered label for crop, timing, protective equipment, weather restrictions, dose, interval and pre-harvest requirements.',avoid:['Do not increase concentration beyond the product label.','Do not randomly mix crop-protection products.','Do not spray the whole field automatically when the affected area has not been confirmed.','Do not rely on the AI confidence score as a substitute for the registered product label or expert confirmation.'],prevention:['Inspect older leaves regularly.','Remove infected crop debris using locally recommended sanitation practices.','Avoid prolonged leaf wetness where practical.','Maintain plant spacing and airflow according to crop recommendations.','Record affected rows and revisit them after action.']},
    te:{title:'మీ టమాటా ఆకులో Early Blight అనుమానానికి సరిపడే లక్షణాలు కనిపిస్తున్నాయి',meaning:'Early Blight సాధారణంగా పాత ఆకులపై గోధుమ రంగు మచ్చలుగా మొదలై వలయాల్లా కనిపించవచ్చు. లక్షణాలు పెరిగితే ఆకులు దెబ్బతిని మొక్క ఆరోగ్యకరమైన పెరుగుదలపై ప్రభావం పడవచ్చు. ఇది AI స్క్రీనింగ్ ఫలితం మాత్రమే కాబట్టి ముఖ్యమైన చికిత్స నిర్ణయాన్ని ధృవీకరించాలి.',seriousness:'మచ్చలు పెరుగుతున్నప్పుడు లేదా పక్కనున్న అనేక మొక్కల్లో అదే లక్షణం కనిపించినప్పుడు త్వరగా చర్య తీసుకోండి.',now:['పాత ఆకులపై పెరుగుతున్న గోధుమ మచ్చలు మరియు వలయాల్లాంటి నమూనాలు ఉన్నాయా చూడండి.','బాగా ప్రభావితమైన మొక్క భాగాలను స్థానిక పంట సూచనల ప్రకారం తొలగించి ఆరోగ్యమైన మొక్కల దగ్గర వదలకండి.','అదే వరుస లేదా జోన్‌లోని పక్క మొక్కలను కూడా పరిశీలించండి.','సాధ్యమైనంత వరకు ఆకులు ఎక్కువసేపు తడిగా ఉండకుండా చూడండి; తడి ఆకుల మధ్య అనవసరంగా తిరగకండి.'],field:'ఫీల్డ్ పరిశుభ్రత, బాగా ప్రభావితమైన భాగాల తొలగింపు, క్రమమైన పర్యవేక్షణ మరియు ఆకులపై ఎక్కువసేపు తేమ నిలవకుండా చేసే పద్ధతులకు ప్రాధాన్యం ఇవ్వండి.',bio:'టమాటా Early Blight కోసం ధృవీకరించిన స్థానిక వ్యవసాయ వనరు లేదా నిపుణుడు ప్రత్యేకంగా సిఫారసు చేసినప్పుడే బయాలాజికల్ ఆప్షన్ వాడండి.',chemical:'వ్యాధిని ధృవీకరించిన తర్వాత మాత్రమే, స్థానికంగా నమోదు చేసిన లేబుల్ లేదా అర్హత గల వ్యవసాయ నిపుణుడి సూచన ప్రకారం కెమికల్ ఆప్షన్ వాడండి. AgriGuardian X పురుగుమందు పేరు, కాన్సన్‌ట్రేషన్ లేదా డోస్‌ను ఊహించి చెప్పదు.',apply:'ధృవీకరించిన సూచన లక్ష్యిత చర్యను అనుమతిస్తే ప్రభావిత మొక్క లేదా జోన్‌కే చికిత్స చేయండి. పంట, సమయం, రక్షణ పరికరాలు, వాతావరణ పరిమితులు, డోస్, ఇంటర్వల్ మరియు harvest ముందు గడువు కోసం నమోదు చేసిన లేబుల్‌ను పాటించండి.',avoid:['లేబుల్‌లో ఉన్నదానికంటే కాన్సన్‌ట్రేషన్ పెంచకండి.','పంట రక్షణ ఉత్పత్తులను యాదృచ్ఛికంగా కలపకండి.','ప్రభావిత ప్రాంతం నిర్ధారించకుండా మొత్తం పొలానికి ఆటోమేటిక్‌గా స్ప్రే చేయకండి.','AI confidence ను లేబుల్ లేదా నిపుణుడి ధృవీకరణకు బదులుగా ఉపయోగించకండి.'],prevention:['పాత ఆకులను క్రమం తప్పకుండా పరిశీలించండి.','స్థానికంగా సిఫారసు చేసిన పద్ధతిలో ప్రభావిత అవశేషాలను తొలగించండి.','సాధ్యమైనంత వరకు ఆకులు ఎక్కువసేపు తడిగా ఉండకుండా చూడండి.','పంట సూచనలకు అనుగుణంగా మొక్కల మధ్య గాలి ప్రసరణ ఉండేలా చూడండి.','ప్రభావిత వరుసలను రికార్డు చేసి చర్య తర్వాత మళ్లీ పరిశీలించండి.']}
  },
  late:{
    source:{name:'TNAU Agritech Portal — Tomato diseases',url:'https://agritech.tnau.ac.in/crop_protection/crop_prot_crop%20diseases_veg_tomato.html'},
    revisit:[2,3],
    en:{title:'Your tomato leaf shows a pattern consistent with suspected Late Blight',meaning:'Late blight can produce rapidly expanding water-soaked or brown lesions and may spread quickly when weather is favourable. Because similar symptoms can have other causes, treat this as a screening alert that needs prompt confirmation.',seriousness:'This condition can progress quickly under favourable weather, so inspect the affected zone promptly.',now:['Inspect both leaf surfaces and nearby stems for rapidly expanding lesions.','Mark and separate the affected row or zone for close monitoring.','Check nearby tomato plants immediately for similar symptoms.','Avoid moving through wet foliage unnecessarily and seek prompt local confirmation before treatment.'],field:'Prioritise rapid scouting, affected-zone marking, sanitation and reduction of practices that unnecessarily move moisture or contaminated plant material between rows.',bio:'Use a biological option only when it is specifically recommended for confirmed tomato late blight by a verified local agricultural source or qualified expert.',chemical:'Late blight treatment can be time-sensitive, but the product and dose must come from a locally registered label or qualified agricultural recommendation. The AI must not generate a chemical dose.',apply:'After confirmation, follow the registered product label exactly for crop, disease, timing, protective equipment, weather restrictions, application interval, dose and pre-harvest requirements. Record the treated row or zone for revisit.',avoid:['Do not delay confirmation when symptoms are spreading rapidly.','Do not increase dose beyond the registered label.','Do not mix products unless the label expressly permits it.','Do not move infected wet plant material through healthy rows.'],prevention:['Scout during cool or humid risk periods.','Inspect nearby plants as soon as a suspicious lesion is found.','Keep field sanitation records and affected-zone history.','Use locally recommended resistant material and crop-protection practices where applicable.','Revisit the same marked plants after action.']},
    te:{title:'మీ టమాటా ఆకులో Late Blight అనుమానానికి సరిపడే లక్షణాలు కనిపిస్తున్నాయి',meaning:'Late Blight వేగంగా పెరిగే నీటితో తడిసినట్లున్న లేదా గోధుమ రంగు మచ్చలను కలిగించవచ్చు మరియు అనుకూల వాతావరణంలో వేగంగా వ్యాపించవచ్చు. ఇలాంటి లక్షణాలకు ఇతర కారణాలు కూడా ఉండవచ్చు కాబట్టి దీన్ని వెంటనే ధృవీకరించాల్సిన స్క్రీనింగ్ అలర్ట్‌గా చూడండి.',seriousness:'అనుకూల వాతావరణంలో ఇది వేగంగా పెరగవచ్చు కాబట్టి ప్రభావిత జోన్‌ను వెంటనే పరిశీలించండి.',now:['ఆకుల రెండు వైపులా మరియు పక్కనున్న కాండాలపై వేగంగా పెరుగుతున్న మచ్చలు ఉన్నాయా చూడండి.','ప్రభావిత వరుస లేదా జోన్‌ను గుర్తించి దగ్గరగా పర్యవేక్షించండి.','పక్కనున్న టమాటా మొక్కలను వెంటనే పరిశీలించండి.','తడి ఆకుల మధ్య అనవసరంగా తిరగకండి మరియు చికిత్సకు ముందు స్థానిక ధృవీకరణ త్వరగా పొందండి.'],field:'వేగమైన స్కౌటింగ్, ప్రభావిత జోన్ గుర్తింపు, పరిశుభ్రత మరియు వరుసల మధ్య తేమ లేదా ప్రభావిత మొక్క పదార్థం అనవసరంగా తరలకుండా చేసే చర్యలకు ప్రాధాన్యం ఇవ్వండి.',bio:'ధృవీకరించిన టమాటా Late Blight కోసం స్థానిక అధికారిక వ్యవసాయ వనరు లేదా అర్హత గల నిపుణుడు సిఫారసు చేసినప్పుడే బయాలాజికల్ ఆప్షన్ వాడండి.',chemical:'Late Blight చికిత్సకు వేగం అవసరం కావచ్చు, కానీ ఉత్పత్తి మరియు డోస్ స్థానికంగా నమోదు చేసిన లేబుల్ లేదా అర్హత గల వ్యవసాయ సూచన నుంచే రావాలి. AI కెమికల్ డోస్‌ను సృష్టించకూడదు.',apply:'ధృవీకరణ తర్వాత పంట, వ్యాధి, సమయం, రక్షణ పరికరాలు, వాతావరణ పరిమితులు, అప్లికేషన్ ఇంటర్వల్, డోస్ మరియు harvest ముందు గడువు కోసం నమోదు చేసిన లేబుల్‌ను ఖచ్చితంగా పాటించండి. మళ్లీ పరిశీలించేందుకు చికిత్స చేసిన వరుస లేదా జోన్‌ను రికార్డు చేయండి.',avoid:['లక్షణాలు వేగంగా పెరుగుతున్నప్పుడు ధృవీకరణను ఆలస్యం చేయకండి.','నమోదు చేసిన లేబుల్ కంటే డోస్ పెంచకండి.','లేబుల్ స్పష్టంగా అనుమతించకపోతే ఉత్పత్తులను కలపకండి.','తడి ప్రభావిత మొక్క పదార్థాన్ని ఆరోగ్యమైన వరుసల మధ్య తీసుకెళ్లకండి.'],prevention:['చల్లని లేదా తేమ ఎక్కువగా ఉన్న ప్రమాద కాలాల్లో పర్యవేక్షించండి.','అనుమానాస్పద మచ్చ కనిపించగానే పక్క మొక్కలను పరిశీలించండి.','ఫీల్డ్ పరిశుభ్రత మరియు ప్రభావిత జోన్ చరిత్రను రికార్డు చేయండి.','అనువైనప్పుడు స్థానికంగా సిఫారసు చేసిన నిరోధక రకాలు మరియు పంట రక్షణ పద్ధతులు వాడండి.','చర్య తర్వాత అదే గుర్తించిన మొక్కలను మళ్లీ పరిశీలించండి.']}
  }
};

export function getGuidance(key,lang='en'){const entry=FARMER_GUIDANCE[key]||FARMER_GUIDANCE.healthy;return {...entry[lang],source:entry.source,revisit:entry.revisit,key};}
export function revisitText(key,lang='en'){const g=getGuidance(key,lang),[min,max]=g.revisit;return lang==='te'?`ఈ మొక్కను ${min}–${max} రోజుల్లో మళ్లీ పరిశీలించండి.`:`Recheck this same plant in ${min}–${max} days.`;}
export function speechText(key,lang='en'){const g=getGuidance(key,lang);return [g.title,g.meaning,g.seriousness,lang==='te'?'ఇప్పుడు చేయాల్సినవి':'What to do now',...g.now,lang==='te'?'జాగ్రత్తలు':'Please avoid',...g.avoid,revisitText(key,lang)].join('. ');}
